# Generated by Django 5.1 on 2024-08-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newborn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', null=True, upload_to=''),
        ),
    ]
